task 1...8 согласно ТЗ (Баннов Даниил)
bannovdaniil/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-08 20:08 UTC by bannovdaniil

Провел небольшой рефакторинг,

task1 - вынес Set в Map, тогда будет линейное время O(n), против логорифмического O(lon(n)), если в сриме искать постоянно по ID.
task2 - стрим без наворотов.
task3 - сортировка.
task4 - просто map
task5 - просто map v2
task6 - очень интересная задача над которой пришлось поломать голову, т.к. тут не было требования как в task1 к времени выполнения, сделал без дополнительного Map, для разнообразия. (в коммитах есть 3 варианта этой задачи, без стрима, с мапой, и последняя )
task7 - flatMap
task8 - творческая задача, комментарии по коду в коммите. (нарисовал небольшие тесты для этого чудо кода)

2022-12-08 20:11 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -/*
комментарии все убрал,
в каждом методе где приходят в параметрах коллекции добавленна проверка на null, по аналогии с первым методом.
имена некоторых методов поменял.

2022-12-08 20:11 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        return persons.stream()
заменил на стрим с пропуском первой записи.

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -    String result = "";
String изменил на StringBuilder. Это быстрее работает. и при соединении имен добавил пробел.

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        appendNameIfNotNullWithSpace(person.getFirstName(), fullName);
DRY - don't repeat you self, вынес повторяющиеся куски кода в отдельный метод.

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        return persons.stream()
поменял спагетти код на красивый стим.

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        return !Collections.disjoint(persons1, persons2);
супер метод все делает сам. быстро и лаконично.

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -    return persons.stream().map(Person::getFirstName).collect(Collectors.toList());
смысл гонять стрим, если можно использовать магию конструктора HashSet

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -  }
изначально подумал, что метод тут не к месту, но с другой стороны только приватная переменная класса, которая без геттеров и сеттеров, тут точно не нужна, а гонять стрим, для инкримента это сильно :)

2022-12-08 20:18 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -  public Set<String> getDifferentNames(List<Person> persons) {
Different и Unique , все таки разное значение и смысл в том числе тоже.

2022-12-12 05:18 UTC, genroelgvozo requested changes

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/common/PersonConverter.java
> +    ApiPersonDto convert(Person person);
кто-то меня плохо слушал)
 
ты приходишь в проект, и меняешь версии либы, добавляешь чекстал, меняешь форматирование, это ок?)

я хочу видеть в ПР изменения связанные только с задачами.

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +                .filter(person -> person.getFirstName() != null)
а это зачем?

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +                .collect(Collectors.toSet());
тут будет O(n*m) где n кол-во ареек привязанных к персонам, а m кол-во всего ареек (а это очень много может быть)
можно за О(n+m)

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        return persons.stream()
а чем лучше?

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        appendNameIfNotNullWithSpace(person.getFirstName(), fullName);
это хорошо, но в целом получается библиотечный код, который не просто читать, который погружает в технические детали (из-за чего как раз легко было ошибиться с пробелом в начале)

хочется код, который не говорит "как делать", а говорит "что делать". Конечно можно и так написать, но глянь ка на Collectors.joining()

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +        return !Collections.disjoint(persons1, persons2);
а если два листа передали, быстро будет?

можно ли ускорить гарантированно, пускай за счет памяти?

2022-12-12 05:18 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> -  }
а в чем сила то?)

2022-12-12 16:43 UTC, bannovdaniil commented on src/main/java/tasks/Task6.java
> +                .collect(Collectors.toSet());
была такая реализация, вернул в релиз.

2022-12-12 17:14 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        return persons.stream()
Прежде всего, убрано remove(0), менять, входящие переменные не самая лучшая практика. А также удаление первого элемента, для некоторых коллекций может увеличить время выполнения на O(n) для перемещение элементов. 
А по коду более понятно, и наглядно.

2022-12-12 17:32 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        appendNameIfNotNullWithSpace(person.getFirstName(), fullName);
Спасибо за подсказку, взял на заметку.
Код и тесты переписал.

2022-12-12 17:36 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> +        return !Collections.disjoint(persons1, persons2);
за счет памяти можно.

2022-12-12 17:57 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -  }
Сила в правде... Вот мое предположение, любой код имеет право на жизнь, тут сложно оценивать, с какой целью автор изначально использовал данную переменную. Если нет геттеров и сеттеров, то возможно для внутренних нужд, т.к. ни в одном из методов класса она больше не используется, возможно, это просто жертва рефакторинга.
 Предположим, что она все еще нам необходима, тогда более логично смотрится:
 
 count = numbers.filter(number -> number % 2 == 0).count();
 
 стрим сам производит вычисления при этом максимально быстро, так же если данный поток будет многопоточным, это не вызовет проблем, с volatile.

2022-12-12 18:11 UTC, bannovdaniil commented on src/main/java/common/PersonConverter.java
> +    ApiPersonDto convert(Person person);
хотел как лучше, а получилось не очень.
это из-за отсутствия такого опыта, спасибо Олег, что внес ясность, лучше на учебе такое узнать, чем потом на проде!
сделал git rebase -i
все вернул к первоначальному виду.

2022-12-12 18:42 UTC, bannovdaniil commented on src/main/java/tasks/Task3.java
> +                .filter(person -> person.getFirstName() != null)
На случай если в коллекции попадется null объект, все на null проверяется и этот случай попытался учесть.
переписал на более красивое:
                 .filter(Objects::nonNull)
в тест добавил обработку подобной ситуации.

2022-12-13 06:27 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +                .filter(person -> person.getFirstName() != null)
так вот именно, я просто не понял, ты имя с null сравнивал а не персону).
А .filter(Objects::nonNull) теперь фильтрует что ты и хотел

2022-12-13 06:29 UTC, genroelgvozo commented on README.md
> +6. ...
Вопрос - а это зачем в редми?)
редми - описание как работает сервис, что надо сделать, или как запустить. Но точно не чья-то история по дням)

2022-12-13 06:31 UTC, genroelgvozo requested changes

2022-12-13 06:31 UTC, genroelgvozo commented on src/main/java/common/PersonConverter.java
> +    ApiPersonDto convert(Person person);
чето не вернул никуда

2022-12-13 06:31 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    private final PersonService personService;
все форматирование все равно меняешь, ребейз не помог)

2022-12-13 06:31 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> -  public Set<String> getDifferentNames(List<Person> persons) {
а distinct?)

2022-12-13 11:39 UTC, bannovdaniil commented on src/main/java/tasks/Task8.java
> -  public Set<String> getDifferentNames(List<Person> persons) {
могу предположить, что т.к. слово UNIQUE в базах уже занято под описание поля пришлось, что-то придумывать. Англичанам виднее от чего это было выбрано distinct, это тонкости перевода,
distinct = unique
 
![image](https://user-images.githubusercontent.com/96119195/207308085-a0080b90-bd96-442f-bd8c-2f5a2484e389.png)

2022-12-13 12:57 UTC, merged